
(function(){
"use strict";
function hi(){try{return AREA==="highway"||AREA==="highway_loop"}catch(e){return false}}
function toast(t){try{if(typeof showToast==="function")showToast(t)}catch(e){}}
function ld(){try{return DEPTH.LABEL+160}catch(e){return 5200}}
function cd(){try{return DEPTH.CHARACTER_BASE+260}catch(e){return 2600}}
function ang(h){return h+180}
function key(sc){if(sc.emsTrafficTextureKeys&&sc.emsTrafficTextureKeys.length>1)return sc.emsTrafficTextureKeys[1];if(sc.trafficTextureKeys&&sc.trafficTextureKeys.length)return sc.trafficTextureKeys[0];return"donny_car"}
class CivicPatrolManager{
 constructor(sc,traffic){this.scene=sc;this.traffic=traffic;this.heat=Number(localStorage.getItem("cf_v117_heat")||localStorage.getItem("cf_v116_heat")||"0");this.level=Number(localStorage.getItem("cf_v117_wanted")||localStorage.getItem("cf_v116_wanted")||"0");this.units=[];this.blocks=[];this.spawnCd=0;this.blockCd=0;this.decay=0;this.hud=this.makeHud()}
 makeHud(){let e=document.getElementById("civicWantedHud");if(!e){e=document.createElement("div");e.id="civicWantedHud";e.style.cssText="position:fixed;left:calc(env(safe-area-inset-left) + 6px);top:calc(env(safe-area-inset-top) + 128px);z-index:24;padding:4px 6px;border:1px solid rgba(255,80,80,.45);background:rgba(20,2,2,.55);color:#ffb3b3;font:8px monospace;pointer-events:none;text-shadow:0 0 4px #f00;";document.body.appendChild(e)}return e}
 save(){localStorage.setItem("cf_v117_heat",String(this.heat));localStorage.setItem("cf_v117_wanted",String(this.level))}
 addHeat(a,r="crime"){this.heat=Math.max(0,this.heat+a);let old=this.level;this.level=Phaser.Math.Clamp(Math.floor(this.heat/2),0,5);this.save();if(this.level>old){toast(`CIVIC PATROL ALERT\nWANTED ${this.level}: ${r}`);this.spawnUnit(true);if(this.level>=2)this.spawnBlock(true)}}
 hudUpdate(){if(!this.hud)return;const s="★".repeat(this.level)+"☆".repeat(5-this.level);this.hud.innerHTML=`<span style="color:#ff7777">CIVIC PATROL</span><br>WANTED ${s}<br><span style="color:#ffcccc">UNITS ${this.units.length} RB ${this.blocks.length}</span>`}
 target(){const s=this.scene;return s.vehicleMode&&s.vehicle?s.vehicle:s.player}
 ensure(){if(!hi())return;this.hudUpdate();if(this.level>0&&this.units.length<Math.min(this.level+1,4))this.spawnUnit(false);if(this.level>=2&&this.blocks.length<1)this.spawnBlock(false)}
 siren(){const s=this.scene;try{if(s.cache.audio.exists("veh_civic_blip"))s.sound.play("veh_civic_blip",{volume:.42});else if(s.cache.audio.exists("veh_police"))s.sound.play("veh_police",{volume:.28})}catch(e){}}
 spawnUnit(force=false){if(!hi()||(!force&&this.spawnCd>0))return;const s=this.scene,t=this.target();if(!t)return;const car=s.add.image(Phaser.Math.Clamp(t.x+(Math.random()>.5?110:-110),60,s.mapW-60),Phaser.Math.Clamp(t.y+(t.y<s.mapH*.5?280:-280),60,s.mapH-60),key(s)).setDepth(cd()).setScale(.92).setOrigin(.5,.5);car.kind="Civic Patrol";car.heading=t.y<s.mapH*.5?90:-90;car.speed=0;car.hitCd=0;car.label=s.add.text(car.x,car.y-70,"CIVIC PATROL",{fontFamily:"monospace",fontSize:"8px",color:"#ffb3b3",backgroundColor:"rgba(0,0,0,.70)",padding:{x:4,y:2}}).setOrigin(.5).setDepth(ld());this.units.push(car);this.spawnCd=1600;this.siren()}
 spawnBlock(force=false){if(!hi()||(!force&&this.blockCd>0))return;const s=this.scene,t=this.target();if(!t)return;const y=Phaser.Math.Clamp(t.y-260,90,s.mapH-90),xs=[s.mapW*.36,s.mapW*.50,s.mapW*.64],b={cars:[],y};xs.forEach((x,i)=>{const car=s.add.image(x,y+(i%2?18:-18),key(s)).setDepth(cd()+5).setScale(.92).setOrigin(.5,.5);car.kind="Roadblock";car.angle=i===1?90:270;car.hitCd=0;car.label=s.add.text(car.x,car.y-70,i===1?"ROADBLOCK":"PATROL",{fontFamily:"monospace",fontSize:"8px",color:"#ffcccc",backgroundColor:"rgba(0,0,0,.70)",padding:{x:4,y:2}}).setOrigin(.5).setDepth(ld());b.cars.push(car)});this.blocks.push(b);this.blockCd=9000;toast("CIVIC ROADBLOCK\nBreak through or turn away");this.siren()}
 ram(u,isBlock=false){const s=this.scene;if(!s.vehicleMode||!s.vehicle)return;const d=Phaser.Math.Distance.Between(s.vehicle.x,s.vehicle.y,u.x,u.y);if(d>=88)return;const nx=(s.vehicle.x-u.x)/(d||1),ny=(s.vehicle.y-u.y)/(d||1);s.vehicle.x+=nx*(isBlock?20:12);s.vehicle.y+=ny*(isBlock?20:12);s.vehicleSpeed=(s.vehicleSpeed||0)*(isBlock?.45:.70);u.hitCd=Math.max(0,(u.hitCd||0)-16);if(u.hitCd<=0){u.hitCd=900;this.addHeat(isBlock?.35:.15,isBlock?"roadblock hit":"ramming patrol");try{if(s.cache.audio.exists("veh_crash"))s.sound.play("veh_crash",{volume:.35})}catch(e){}}}
 update(delta){if(!hi())return;this.spawnCd=Math.max(0,this.spawnCd-(delta||16));this.blockCd=Math.max(0,this.blockCd-(delta||16));this.decay+=(delta||16);this.hudUpdate();const s=this.scene,t=this.target();if(!t)return;if(this.level>0&&this.units.length<Math.min(this.level+1,4)&&this.spawnCd<=0)this.spawnUnit(false);if(this.level>=2&&this.blocks.length<1&&this.blockCd<=0)this.spawnBlock(false);let near=false;this.units=this.units.filter(u=>{const dx=t.x-u.x,dy=t.y-u.y,dist=Math.hypot(dx,dy)||1;if(dist<380)near=true;const want=Phaser.Math.RadToDeg(Math.atan2(dy,dx));u.heading+=Phaser.Math.Angle.ShortestBetween(u.heading,want)*.06;u.speed=Phaser.Math.Clamp((u.speed||0)+(delta||16)*.013,0,255+this.level*18);const r=Phaser.Math.DegToRad(u.heading);u.x+=Math.cos(r)*u.speed*((delta||16)/1000);u.y+=Math.sin(r)*u.speed*((delta||16)/1000);u.angle=ang(u.heading);if(u.label)u.label.setPosition(u.x,u.y-70);this.ram(u,false);if(u.x<-260||u.y<-260||u.x>s.mapW+260||u.y>s.mapH+260){if(u.label)u.label.destroy();u.destroy();return false}return true});this.blocks=this.blocks.filter(b=>{b.cars.forEach(c=>{if(c.label)c.label.setPosition(c.x,c.y-70);this.ram(c,true)});if(Math.abs((t.y||0)-b.y)>620){b.cars.forEach(c=>{try{if(c.label)c.label.destroy();c.destroy()}catch(e){}});return false}return true});if(this.level>0&&this.decay>2500){this.decay=0;if(!near){this.heat=Math.max(0,this.heat-.32);this.level=Phaser.Math.Clamp(Math.floor(this.heat/2),0,5);this.save()}}if(s.vehicleMode&&s.vehicle&&Math.abs(s.vehicleSpeed||0)>260&&Math.random()<.004)this.addHeat(.08,"reckless driving")}
}
window.CFHighwayCivicPatrolManager=CivicPatrolManager;
})();
